### ISSUE TITLE
Unstable output ordering

### ISSUE THREAD

**Issue by novotl** [radeklat/settings-doc#34]
I use a combination of `--module` and `--class` to specify Settings sources. 
The order how they appear in the output is not stable and changes between runs. 
This is especially problematic with pre-commit, which fails if it detects a file change.

I think this can be fixed by sorting 
https://github.com/radeklat/settings-doc/blob/982d3aac06782c09b715dbc4aeba2219bc94ac2b/src/settings_doc/main.py#L148-L150

e.g. with 
```python
sorted(settings, key=str)
```

However, I think keeping the order of Settings classes the same as in the input is more user friendly, in that case I think an ordered set will need to be used.

**Comment by radeklat** [comment]
Hi @novotl, thank you for catching this and suggesting where to fix. I'll have a look.

**Comment by radeklat** [comment]
@novotl, the fix should be available in 4.0.1. I decided to use a `Dict` instead of a `Set` as the keys order is stable (since Python 3.7). So the order won't be alphabetical but in order of the discovered classes. This should allow customising the order by changing it within the files. Please let me know if it still doesn't work for you.
